export const dateIdeas = [
  {
    id: '1',
    title: 'Picnic in the Park',
    description: 'Enjoy a lovely afternoon with a picnic basket, blanket, and your favorite snacks at the nearest park.',
    imageUrl: 'https://images.pexels.com/photos/4577729/pexels-photo-4577729.jpeg',
    category: 'Outdoor',
    duration: '2-3 hours',
    price: '$',
    location: 'City Park',
    distance: '0.8 miles',
    isPremium: false,
  },
  {
    id: '2',
    title: 'Gourmet Coffee Tasting',
    description: 'Sample various coffee blends from around the world while engaging in meaningful conversation.',
    imageUrl: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg',
    category: 'Food & Drink',
    duration: '1-2 hours',
    price: '$$',
    location: 'Artisan Cafe',
    distance: '1.2 miles',
    isPremium: false,
  },
  {
    id: '3',
    title: 'Sunset Beach Walk',
    description: 'Take a leisurely stroll along the beach while watching the sunset paint the sky with beautiful colors.',
    imageUrl: 'https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg',
    category: 'Romantic',
    duration: '1-2 hours',
    price: 'Free',
    location: 'Shoreline Beach',
    distance: '3.5 miles',
    isPremium: false,
  },
  {
    id: '4',
    title: 'Luxury Vineyard Tour',
    description: 'Exclusive access to premium wine tasting with a private sommelier and gourmet cheese pairing.',
    imageUrl: 'https://images.pexels.com/photos/1123260/pexels-photo-1123260.jpeg',
    category: 'Premium',
    duration: '4-5 hours',
    price: '$$$',
    location: 'Hillside Vineyard',
    distance: '12 miles',
    isPremium: true,
  },
  {
    id: '5',
    title: 'Indoor Rock Climbing',
    description: 'Challenge each other with an exciting indoor rock climbing adventure suitable for all skill levels.',
    imageUrl: 'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg',
    category: 'Active',
    duration: '2-3 hours',
    price: '$$',
    location: 'Climb Zone',
    distance: '2.1 miles',
    isPremium: false,
  },
];

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'outdoor', name: 'Outdoor' },
  { id: 'food', name: 'Food & Drink' },
  { id: 'romantic', name: 'Romantic' },
  { id: 'active', name: 'Active' },
  { id: 'cultural', name: 'Cultural' },
  { id: 'virtual', name: 'Virtual' },
  { id: 'premium', name: 'Premium' },
];

export const premiumBenefits = [
  { id: '1', text: 'Access to 200+ exclusive premium date ideas' },
  { id: '2', text: 'Advanced filters for perfect date matching' },
  { id: '3', text: '2x data generation capacity' },
  { id: '4', text: 'Ad-free experience' },
  { id: '5', text: 'Priority customer support' },
];

export const mockSettings = [
  {
    id: 'notifications',
    title: 'Push Notifications',
    subtitle: 'Receive alerts for new date ideas and data updates',
    type: 'toggle',
    icon: 'bell',
  },
  {
    id: 'location',
    title: 'Location Services',
    subtitle: 'Use your location to find nearby experiences',
    type: 'toggle',
    icon: 'map-pin',
  },
  {
    id: 'preferences',
    title: 'Date Preferences',
    subtitle: 'Customize your date recommendations',
    type: 'navigation',
    icon: 'sliders',
  },
  {
    id: 'account',
    title: 'Account Settings',
    subtitle: 'Manage your profile and security',
    type: 'navigation',
    icon: 'user',
  },
  {
    id: 'payment',
    title: 'Payment Methods',
    subtitle: 'Update your payment information',
    type: 'navigation',
    icon: 'credit-card',
  },
  {
    id: 'help',
    title: 'Help & Support',
    subtitle: 'Contact us or browse FAQs',
    type: 'navigation',
    icon: 'help-circle',
  },
  {
    id: 'about',
    title: 'About DateByte',
    subtitle: 'Version 1.0.0',
    type: 'info',
    icon: 'info',
  },
];